# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(max_length=20)),
                ('signal_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('date_acquisition', models.DateField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'signal',
            },
        ),
    ]
