# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('signal_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'signal_type',
            },
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
